### ISSUE TITLE
How do you access Flutter Commands? and best approaches?

### ISSUE THREAD

**Issue by fenchai23** [fluttertools/sidekick#219]
sidekick creates .fvm directory instead of globally like fvm did.

On the flutter project so to access the flutter command you need to dive into the flutter directory it seems?

Is there any way to directly access flutter commands on root directory like fvm allowed me to before?

what's the best approach? or best practices while using sidekick (fvm GUI)

**Comment by aguilaair** [comment]
![image](https://user-images.githubusercontent.com/29983481/168102480-49a9468b-739d-46ec-9927-75deee4d80d6.png)
You can still set a global flutter version as shown. Was that your question?

**Comment by fenchai23** [comment]
yup that was it, thanks
