### ISSUE TITLE
Fix appimage linux GitHub Action

### ISSUE THREAD

**Issue by Vinzent03** [fluttertools/sidekick#223]
I'm currently unsure, whether this project supports Linux or not. You state it in the readme multiple times, but there is no installer in the [new release](https://github.com/fluttertools/sidekick/releases/tag/1.0.0). [0.2.0](https://github.com/fluttertools/sidekick/releases/tag/0.2.0) had one. Your [wiki about installing](https://github.com/fluttertools/sidekick/wiki/Installing) states that Linux is "coming soon".

I'm currently using 0.2.0 on Ubuntu 20.04 and it's working great! Thank you.

**Comment by aguilaair** [comment]
Hey! 

Yes, Sidekick does support Linux, we were having some CI issues and therefore were having issues building the binaries, I will try and see if I can build them manually today.

Wiki-wise, we just haven't had time to write up install instructions, if you could make a quick guide I can put it up :)

**Comment by aguilaair** [comment]
@Vinzent03 I have added the binaries, could you test the app image for me please?

**Comment by Vinzent03** [comment]
@aguilaair When starting via terminal I get the following error:
`(process:134760): GLib-CRITICAL **: 17:54:11.654: g_file_test: assertion 'filename != NULL' failed`

Then I get a pop-up from [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher). After confirming the execution in the pop up I get another message in the terminal:
```
/tmp/.mount_sidekiXy8Thf//Sidekick: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_sidekiXy8Thf//Sidekick)
```
Then the process exists.

**Comment by aguilaair** [comment]
Thanks, I built it with Ubuntu 22.04, so GLIBC_2.34 may not be available in your specific distro and version, I'll try and compile in 18.04 LTS and upload a new one.

Thanks for getting back to me so quickly

**Comment by aguilaair** [comment]
@Vinzent03 updated, can you try now?

**Comment by aguilaair** [comment]
Opened #224

**Comment by Vinzent03** [comment]
The Linux Binaries are missing again in the [1.1.0 release](https://github.com/fluttertools/sidekick/releases/tag/1.1.0). The wiki is still outdated as well.

**Comment by aguilaair** [comment]
The wiki just refers to the guide coming soon, not that the version is coming soon. Feel free to contribute to fix it :)
