### ISSUE TITLE
Sidekick may not launch in some Windows 11 builds

### ISSUE THREAD

**Issue by aguilaair** [fluttertools/sidekick#228]
Current workaround is to run the portable or unsiged version of Sidekick in Windows 8 Compatibility mode, unknown cause.

**Comment by kenicenoel** [comment]
How can it be run in compatibility mode for Windows 8? I'm not seeing this option on right click.

**Comment by aguilaair** [comment]
Properties> Compatibility> Windows 8

**Comment by aguilaair** [comment]
Can you go to the event viewer Windows Logs > Application and see what error is causing the app to crash?

**Comment by kenicenoel** [comment]
> Can you go to the event viewer Windows Logs > Application and see what error is causing the app to crash?

Sure thing. See the information below.
I have uploaded the Report.wer file [here](https://1drv.ms/u/s!Am6RzqfZBL2mx-0d9T9ROAjk7jkycg?e=iShZgP)

1: Information from the error event
Log Name:      Application
Source:        Application Error
Date:          6/22/2022 10:15:54
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      
User:          KENICE-X360\kenic
Computer:      Kenice-x360
Description:
Faulting application name: sidekick.exe, version: 1.0.0.0, time stamp: 0x627cfcda
Faulting module name: sidekick.exe, version: 1.0.0.0, time stamp: 0x627cfcda
Exception code: 0xc000041d
Fault offset: 0x00000000000058a0
Faulting process id: 0x0xAAD0
Faulting application start time: 0x0x1D8864293C6006C
Faulting application path: C:\Program Files\WindowsApps\44484EduardoM.SidekickFlutter_1.0.0.0_x64__s75e7293cm0w2\sidekick.exe
Faulting module path: C:\Program Files\WindowsApps\44484EduardoM.SidekickFlutter_1.0.0.0_x64__s75e7293cm0w2\sidekick.exe
Report Id: 45ad9240-6a85-42fb-a077-a844977faaeb
Faulting package full name: 44484EduardoM.SidekickFlutter_1.0.0.0_x64__s75e7293cm0w2
Faulting package-relative application ID: sidekick
Event Xml:
`<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-22T14:15:54.4148129Z" />
    <EventRecordID>8981</EventRecordID>
    <Correlation />
    <Execution ProcessID="37300" ThreadID="4824" />
    <Channel>Application</Channel>
    <Computer>Kenice-x360</Computer>
    <Security UserID="S-1-5-21-2056601378-3457062421-2058283205-1001" />
  </System>
  <EventData>
    <Data Name="AppName">sidekick.exe</Data>
    <Data Name="AppVersion">1.0.0.0</Data>
    <Data Name="AppTimeStamp">627cfcda</Data>
    <Data Name="ModuleName">sidekick.exe</Data>
    <Data Name="ModuleVersion">1.0.0.0</Data>
    <Data Name="ModuleTimeStamp">627cfcda</Data>
    <Data Name="ExceptionCode">c000041d</Data>
    <Data Name="FaultingOffset">00000000000058a0</Data>
    <Data Name="ProcessId">0xaad0</Data>
    <Data Name="ProcessCreationTime">0x1d8864293c6006c</Data>
    <Data Name="AppPath">C:\Program Files\WindowsApps\44484EduardoM.SidekickFlutter_1.0.0.0_x64__s75e7293cm0w2\sidekick.exe</Data>
    <Data Name="ModulePath">C:\Program Files\WindowsApps\44484EduardoM.SidekickFlutter_1.0.0.0_x64__s75e7293cm0w2\sidekick.exe</Data>
    <Data Name="IntegratorReportId">45ad9240-6a85-42fb-a077-a844977faaeb</Data>
    <Data Name="PackageFullName">44484EduardoM.SidekickFlutter_1.0.0.0_x64__s75e7293cm0w2</Data>
    <Data Name="PackageRelativeAppId">sidekick</Data>
  </EventData>
</Event>`


2. Information from the Information log event

`Fault bucket 1981129138754254672, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: 44484EduardoM.SidekickFlutter_1.0.0.0_x64__s75e7293cm0w2
P2: praid:sidekick
P3: 1.0.0.0
P4: 627cfcda
P5: sidekick.exe
P6: 1.0.0.0
P7: 627cfcda
P8: c000041d
P9: 00000000000058a0
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8925dd53-52ac-47bc-b9cb-2c1e44a878a7.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.cb9fc526-667f-4c7e-8412-c929a467ded6.tmp.WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20220619_1_EC_0_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.904c0961-4c6f-4f25-9686-f72358779edd.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f48c394a-a5a5-4593-9462-f62d4d913b05.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.360b720b-8e9a-4781-ae0e-1015d5cd36a3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c7dc90d8-7d1e-40fc-bfe5-bdb84868e545.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.82b97aeb-3d96-4b6b-aa1f-0b52dbfd9e1f.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_44484EduardoM.Si_846aae847231d21628da4b4b0f6ca6b6621334a_f814c776_915fd0c7-0508-4983-99f3-f52ac54c1354

Analysis symbol: 
Rechecking for solution: 0
Report Id: 45ad9240-6a85-42fb-a077-a844977faaeb
Report Status: 268435456
Hashed bucket: 249d375036c61da80b7e6274899f7750
Cab Guid: 0`

**Comment by aguilaair** [comment]
Have you tried the execuatble in compatibility mode or just the MS Store app?

**Comment by aguilaair** [comment]
Ok, well at least you got it running. Still not sure what the issue is. I'm inclined to think it's Flutter's fault but other Flutter apps do indeed run fine on Windows 11 Insider builds...

**Comment by aguilaair** [comment]
Hey! Are you still having issues? It's opening fine on my computer.

![image](https://user-images.githubusercontent.com/29983481/182388022-c1a4c7a0-f23c-423e-adba-53981d0e3911.png)

**Comment by aguilaair** [comment]
Closing as it seems the release is working fine now on Insider builds

**Comment by Shiba-Kar** [comment]
```Edition	Windows 11 Home Single Language
Version	22H2
Installed on	‎7/‎19/‎2022
OS build	22621.382
Serial number	PF20D0BS
Experience	Windows Feature Experience Pack 1000.22632.1000.0
```

installed sidestick from Microsoft Store latest one not opening

**Comment by aguilaair** [comment]
@Shiba-Kar can you send the event viewer details?

**Comment by rockyprabowo** [comment]
I got the same event message when it crashed. It looks like the crash only happens on Windows 11 Insider Beta (22621 or 22622) and not the current Dev channel (build 25169+).

Here's the event from Event Viewer:
```
Faulting application name: sidekick.exe, version: 1.0.0.0, time stamp: 0x627cfcda
Faulting module name: sidekick.exe, version: 1.0.0.0, time stamp: 0x627cfcda
Exception code: 0xc000041d
Fault offset: 0x00000000000058a0
Faulting process id: 0x0x1BB8
Faulting application start time: 0x0x1D8C2629A866D20
Faulting application path: C:\Program Files\WindowsApps\44484EduardoM.SidekickFlutter_1.0.0.0_x64__s75e7293cm0w2\sidekick.exe
Faulting module path: C:\Program Files\WindowsApps\44484EduardoM.SidekickFlutter_1.0.0.0_x64__s75e7293cm0w2\sidekick.exe
Report Id: f44cd76f-c1da-42f4-9027-05e2b9af87fc
Faulting package full name: 44484EduardoM.SidekickFlutter_1.0.0.0_x64__s75e7293cm0w2
Faulting package-relative application ID: sidekick
```

Here's the information from Windows Problem Reports:
```
Source
A new Flutter project.

Summary
Stopped working

Date
‎07/‎09/‎2022 9:36

Status
Report sent

Description
Faulting Application Path:	C:\Program Files\WindowsApps\44484EduardoM.SidekickFlutter_1.0.0.0_x64__s75e7293cm0w2\sidekick.exe

Problem signature
Problem Event Name:	MoAppCrash
Package Full Name:	44484EduardoM.SidekickFlutter_1.0.0.0_x64__s75e7293cm0w2
Application Name:	praid:sidekick
Application Version:	1.0.0.0
Application Timestamp:	627cfcda
Fault Module Name:	sidekick.exe
Fault Module Version:	1.0.0.0
Fault Module Timestamp:	627cfcda
Exception Code:	c000041d
Exception Offset:	00000000000058a0
OS Version:	10.0.22622.2.0.0.256.164
Locale ID:	14345
Additional Information 1:	86e7
Additional Information 2:	86e714a62d54964f44e802ab89184503
Additional Information 3:	f855
Additional Information 4:	f8557989c6c829b6ae244394a237164c

Extra information about the problem
Bucket ID:	249d375036c61da80b7e6274899f7750 (1981129138754254672)
```

**Comment by aguilaair** [comment]
All crashes have the exact same stack trace attached. It seems 


Frame | Image | Function | Offset
-- | -- | -- | --
0 | sidekick.exe | null | 0x00000000000058A0
1 | sidekick.exe | null | 5B5E
2 | sidekick.exe | null | 0x00000000000061E9
3 | comctl32.dll | CallNextSubclassProc | 0x00000000000000B8
4 | comctl32.dll | MasterSubclassProc | EC
5 | user32.dll | UserCallWinProcCheckWow | 0x000000000000036C
6 | user32.dll | DispatchClientMessage | 0x000000000000009C
7 | user32.dll | __fnINOUTNCCALCSIZE | 0x0000000000000045
8 | ntdll.dll | KiUserCallbackDispatcherContinue | 0x0000000000000000
9 | win32u.dll | ZwUserCreateWindowEx | 0x0000000000000014
10 | user32.dll | VerNtUserCreateWindowEx | 0x0000000000000310
11 | user32.dll | CreateWindowInternal | 0x00000000000001D1
12 | user32.dll | CreateWindowExW | 0x0000000000000082
13 | sidekick.exe | null | 2DA1
14 | sidekick.exe | null | 0x0000000000002114
15 | sidekick.exe | null | 0x00000000000057C2
16 | kernel32.dll | BaseThreadInitThunk | 0x000000000000001D
17 | ntdll.dll | RtlUserThreadStart | 0x0000000000000028

I'm going to continue ivestigating to see why this may be happening. Thank you to everyone who has submitted their reports to MS, they are helping a lot :)

**Comment by nicodumdum** [comment]
Experiencing the same with a fresh install of Windows 11 and fresh install of Sidekick from Windows Store.

Edition	Windows 11 Pro
Version	22H2
Installed on	‎23/‎09/‎2022
OS build	22621.521
Experience	Windows Feature Experience Pack 1000.22634.1000.0

**Comment by aguilaair** [comment]
@nicodumdum does it work with compatibility mode?

**Comment by nicodumdum** [comment]
Hi @aguilaair , yes I tried running it in Windows 8 compatibility but no luck. :(
![Screenshot 2022-09-28 082301](https://user-images.githubusercontent.com/1650987/192660460-69e225c8-a29c-452e-b3de-dcbd6e912a5c.png)

**Comment by aguilaair** [comment]
Ok, I will take a look ASAP

I currently don't have a W11 device

**Comment by gauravmehta13** [comment]
Facing the same issue in 
![image](https://user-images.githubusercontent.com/51997260/193504987-a46b72c8-71a7-4f6f-b56f-713de90daa04.png)

**Comment by Ahmadre** [comment]
> Properties> Compatibility> Windows 8

Thanks @aguilaair :) with compatibility mode on Window 8 it's starting again on 22h2 update :)

**Comment by aguilaair** [comment]
Ok, that's good to know, but what exactly is casuing the issues? I'm honestly very lost...

**Comment by masteradit** [comment]
Facing the same issue, running in compatibility mode did not work :(

**Comment by oliverbytes** [comment]
Running in windows 8 compatibility mode worked only once

**Comment by aguilaair** [comment]
Okay, I now have a device with the W11 H2 Update, let's see what's going on...

**Comment by Rexobias** [comment]
Also facing the same issue. Installed Windows 11 Pro 22H2 yesterday and Flutter Sidekick doesn't start (Windows Store version).

**Comment by aguilaair** [comment]
@Rexobias the new release is currently under review in the Microsoft store, as soon as this gets approved it will start working again.

In the meantime, please download and install the latest version from the releases tab
