### ISSUE TITLE
 mac os execute flutter command  report  "env: bash\r"

### ISSUE THREAD

**Issue by ftc300** [fluttertools/sidekick#231]
<img width="469" alt="image" src="https://user-images.githubusercontent.com/12816061/169490052-2978d6f7-97c2-43ef-adf7-c20e1c61b0b0.png">

**Comment by aguilaair** [comment]
this looks like an issue with CRLF (https://es.wikipedia.org/wiki/CRLF)

**Comment by aguilaair** [comment]
@leoafarias any ideas?

**Comment by ftc300** [comment]
In my case I had a wrong git configuration. 
I change that configuration to

`git config --global core.autocrlf input`
