### ISSUE TITLE
Open in VS code does not open a new VS code window

### ISSUE THREAD

**Issue by tobiasht** [fluttertools/sidekick#233]
When pressing `Open in VS code` i expect the program to open a **new** window of VS code with my project. Instead it "hijacks" one of my currently opened projects. This is really annoying when you for example work on multiple projects or are running the backend locally.

**Comment by aguilaair** [comment]
What OS is this?
It opens new windows in Windows 11

https://user-images.githubusercontent.com/29983481/169992954-592e0457-7405-4b42-b6e9-ef19127f7ae8.mp4

**Comment by tobiasht** [comment]
> What OS is this? It opens new windows in Windows 11


MacOS Monterey 12.3.1 (Latest)

**Comment by aguilaair** [comment]
Can you try the "Custom IDE" mode and selecting the file `Applications/Visual Studio Code.app/Contents/Resources/app/bin/code`?

**Comment by tobiasht** [comment]
In the Applications folder you can only select an application, not the underlaying file structure. So the only thing i can select is  `Applications/Visual Studio Code.app`. 

Still does not work though, it only open a finder window to the project directory.

**Comment by tobiasht** [comment]
Still does not work. When testing in the terminal, you first have to `cd` into the directory and then run `code .`

**Comment by aguilaair** [comment]
The thing is, not everyone has VSCode set in path. So `code .` will not work in all cases, this is the method that is used in Windows and Linux. Maybe Sidekick can check for VSCode in path and use this method which is preferred

**Comment by aguilaair** [comment]
@tobiasht maind checking #243 to see if it resolves the issue?

**Comment by tobiasht** [comment]
I'm on holiday for a month, if you can verify it before that, great, otherwise i will check it out when i get back. Cheers

**Comment by aguilaair** [comment]
I don't have a Mac to test it unfortunately, @leoafarias?

**Comment by aguilaair** [comment]
Hey @tobiasht are you back yet? Leo seems to be a bit out of the loop rn

**Comment by tobiasht** [comment]
It works!

**Comment by tobiasht** [comment]
This seem to not be working anymore unfortunately. On macOS it takes over an opened VS code project, instead of opening a new window. The best workaround for now is to open a new VS code instance before pressing the button.

**Comment by aguilaair** [comment]
What opening method are you using? This behavior is controlled by VSCode when using the URL launch method.

**Comment by aguilaair** [comment]
Please confirm VSCode is in your path. Also, what changed? Did you update to a new version of macOS?
