### ISSUE TITLE
Install Sidekick using Brew

### ISSUE THREAD

**Issue by Shiba-Kar** [fluttertools/sidekick#240]

**Comment by aguilaair** [comment]
This is only possible through cask, which from what I understand is unstable.

Homebrew is designed to install and manage CLI interfaces, not GUIs AFAIK.

**Comment by tsinis** [comment]
> This is only possible through cask, which from what I understand is unstable.
> 
> Homebrew is designed to install and manage CLIs, not GUIs AFAIK.
> 
> Edit: Adding `wontfix` for the time being, may remove later cc @leoafarias

Actually, this feature could be helpful. [Homebrew Cask](https://formulae.brew.sh/cask) is pretty mature, not sure where this "unstable" statement comes from. There are a lot of Cask tools already there: VS Code, Google Chrome, Dropbox, VLC, etc. Totally more than 4145 casks are available right now.

**Comment by aguilaair** [comment]
When I first checked I seem to remember seeing experimental notices. These have now disappeared, I will reopen the issue!
