### ISSUE TITLE
Add --use parameter for one-time execution like flutter create

### ISSUE THREAD

**Issue by timshadel** [fluttertools/sidekick#252]
I'd really like to be able to do this:

`fvm --use 3.0.5 flutter create ....`

Version 1 of this would simply run command X with the given version, or fail if the version is not installed.

Version 2: I have no idea if you could easily see that it's creating a new package or app, and then run the code to add the `.fvm` folder when it's done. That'd be great.

The workaround I have now is to create a new directory for the app, `fvm use --force`, create the new app using `.` as the directory name. This works, but it just isn't as intuitive.

**Comment by aguilaair** [comment]
I am closing this issue as it is not related to Sidekick (the GUI). Please file an issue here: https://github.com/fluttertools/fvm
