### ISSUE TITLE
bug UI on macOS 13 (ventura)

### ISSUE THREAD

**Issue by abehbatre** [fluttertools/sidekick#255]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/36602270/192132291-3e20b333-67cc-45f9-864a-1409a03de120.png">

**Comment by CripyIce** [comment]
Same here.. Resizing the top part of the window seems to fix it temporarily.

**Comment by Ahmadre** [comment]
I got more infos here:

![ezgif com-gif-maker (11)](https://user-images.githubusercontent.com/18512224/201546467-88516fd0-df96-4a9a-8de3-7dcd857e5ae8.gif)

<img width="311" alt="Bildschirm­foto 2022-11-13 um 22 52 36" src="https://user-images.githubusercontent.com/18512224/201546479-571802ce-a4a2-44a6-8962-1e232c089008.png">

**Comment by Ahmadre** [comment]
<img width="1314" alt="Bildschirm­foto 2022-11-13 um 23 28 11" src="https://user-images.githubusercontent.com/18512224/201547797-5c43a6a7-9d6d-435f-a611-f985934eab49.png">

Ok this is the cause of the issue, but it worked earlier...I will have a look at the latest api for Ventura

**Comment by Ahmadre** [comment]
Solved :) @aguilaair :3 (PR will follow)

https://user-images.githubusercontent.com/18512224/201548552-b891e5db-5e88-4893-9774-383289a619f9.mov

**Comment by Ahmadre** [comment]
Please follow and upvote: https://github.com/fluttertools/sidekick/pull/266

**Comment by Ahmadre** [comment]
@abehbatre I solved it. Please download Version 1.1.1 :)
