### ISSUE TITLE
[Windows]: Since Windows 11 h22h2 Update - not starting anymore

### ISSUE THREAD

**Issue by Ahmadre** [fluttertools/sidekick#259]
I encountered, that sidekick isn't starting anymore since I updated to windows 11 h22h2.

I tried the official 1.0.0 on Windows-Store.

I tried without and with Admin-Rights, but none of them are starting sidekick :/

**Comment by aguilaair** [comment]
Duplicate of #228 

I'm really not sure what may be going on, any help would be appreciated...
