### ISSUE TITLE
[Windows]: Version in app wrong (0.2.0 rather then -> 1.0.0)

### ISSUE THREAD

**Issue by Ahmadre** [fluttertools/sidekick#260]
I downloaded the Windows App on App-Store for Windows and there it was labeled with: 1.0.0.

But inside of Sidekick I see this:

<img width="409" alt="image" src="https://user-images.githubusercontent.com/18512224/193666670-3b5590d1-7c41-42ab-9624-cc1c05f2fbba.png">

**Comment by Ahmadre** [comment]
For reference, see these changes from Flutter > 3.3.*

<img width="758" alt="image" src="https://user-images.githubusercontent.com/18512224/193666932-f82cc954-2a3e-4907-9023-6f174d52ca81.png">

https://medium.com/flutter/whats-new-in-flutter-3-3-893c7b9af1ff

**Comment by aguilaair** [comment]
Will be fixed in new version
