### ISSUE TITLE
Sidekick 1.1.1 signed not found

### ISSUE THREAD

**Issue by dimitri-colignon** [fluttertools/sidekick#267]
Hello,
The sidekick 1.1.1 package msix for windows is not signed, I can't install it
Thanks

**Comment by aguilaair** [comment]
This release was mostly for fixing macOS, so I haven't pushed it to the MS Store; therefore, it's not signed. I will send it to MS today and update once the signed package is available

**Comment by dimitri-colignon** [comment]
ok, thank you very much for your work ;-)

**Comment by aguilaair** [comment]
Uploaded :)
