### ISSUE TITLE
How to fix this

### ISSUE THREAD

**Issue by satishs22** [fluttertools/sidekick#294]
Environmental path
![image](https://github.com/fluttertools/sidekick/assets/124110600/03ea6c53-1a00-4c0c-8134-a2a51cef0936)
Flutter doctor -v
![image](https://github.com/fluttertools/sidekick/assets/124110600/bbf22618-0de0-48b6-9073-fd3a3e974567)

**Comment by aguilaair** [comment]
This seems like more of an FVM issue, but can you send a screenshot of your versions?

<img width="237" alt="image" src="https://github.com/fluttertools/sidekick/assets/29983481/59cfd38a-4c15-405e-999a-8037e195dce2">

**Comment by satishs22** [comment]
this thing? @aguilaair 
![image](https://github.com/fluttertools/sidekick/assets/124110600/8fb7ec72-9084-48b0-a406-66ebbe6900f6)

**Comment by aguilaair** [comment]
Is it solved then?

**Comment by aguilaair** [comment]
Can you ensure there are no other fvm/flutter related entries in your PATH

**Comment by aguilaair** [comment]
I'm closing this issue because we have received no response, and the use had previously closed it.

**Comment by Linloir** [comment]
I'm facing the same issue here,
path set to "%USERPROFILE%\fvm\default\bin", and flutter doctor gives the same warning
![image](https://github.com/fluttertools/sidekick/assets/30849181/02e68e59-659e-4388-af99-685258aa47fd)
![image](https://github.com/fluttertools/sidekick/assets/30849181/ebcad0f0-9b91-4fdb-b1ba-e09323a8a3b2)
![image](https://github.com/fluttertools/sidekick/assets/30849181/4b9ea366-d838-418c-861d-5da0addb2fbe)
