### ISSUE TITLE
[Chore] - Review Pub dependencies pointing to git

### ISSUE THREAD

**Issue by leoafarias** [fluttertools/sidekick#299]
Because Sidekick started early on Flutter Desktop, we have accumulated our fair share of dependencies that are pointing directly to Git, different branches or commits. It would be important to review them and know if they are still needed.

- material_floating_search_bar
- i18next
- open_file
- window_size
- FVM -- Awaiting new release due to conflict with `msix`, which depends on a newer (incompatible) version of `cli_util`

**Comment by charles0122** [comment]
@leoafarias We can close this issue.
