### ISSUE TITLE
showing the wrong flutter version even though im adding flutter version 1.20.4

### ISSUE THREAD

**Issue by satishs22** [fluttertools/sidekick#301]
![image](https://github.com/fluttertools/sidekick/assets/124110600/631b3b46-0efa-47c7-9a95-4a4b0e838ec9)

**Comment by aguilaair** [comment]
Could you run flutter doctor on that directory and check what version of flutter is actually located there? It might be an IDE issue.

**Comment by aguilaair** [comment]
Feel free to re-open with new details
