### ISSUE TITLE
Not updating to a new version

### ISSUE THREAD

**Issue by Skmlnv** [fluttertools/sidekick#305]
Trying to upgrade to 3.10.6 but can't do it.
<img width="724" alt="Снимок экрана 2023-08-13 в 00 02 36" src="https://github.com/fluttertools/sidekick/assets/41055933/757feee4-0585-4280-a215-27e631e36a35">

**Comment by hiroshihorie** [comment]
I'm seeing similar issue

**Comment by aguilaair** [comment]
Is this a suplicate of https://github.com/fluttertools/sidekick/issues/280?

**Comment by hiroshihorie** [comment]
Ah looks like duplicate

**Comment by aguilaair** [comment]
I'm going to close the issue. Let me know if it needs to be reopened
