### ISSUE TITLE
Can not open Sidekick - “Sidekick” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by mirabo-vuong-nt** [fluttertools/sidekick#309]
After download from this [link](https://github.com/fluttertools/sidekick/releases/tag/1.1.1), i install Sidekick and open it.
But i got a error message: 
![Screenshot 2023-11-10 at 11 29 18](https://github.com/fluttertools/sidekick/assets/123710038/0c172b70-88f7-4487-81c2-21be5314bd3d)

**Comment by aguilaair** [comment]
https://github.com/fluttertools/sidekick/wiki/Installing#installing-with-dmg-recommended
