### ISSUE TITLE
why does isFvmInstalled() check for git executable 

### ISSUE THREAD

**Issue by prasadsunny1** [fluttertools/sidekick#312]
I was exploring how sidekick executes shell commands and found isFvmInstalled check for `git`, I think its a mistake and it should be checking for `fvm` instead. 

https://github.com/fluttertools/sidekick/blob/356124bea7bc3c9bcd0373f1903a836d2204c569/lib/src/modules/compatibility_checks/compat.utils.dart#L23C2-L29C2

```
Future<bool> isFvmInstalled() async {
  final fvmRes = await which("git");
  if (fvmRes != null) {
    return true;
  }
  return false;
}
```

**Comment by aguilaair** [comment]
yep! FVM comes included with Sidekick so the check might not even be needed

**Comment by charles0122** [comment]
@aguilaair We can close this issue.
