### ISSUE TITLE
In CHINA Internal Error: Could Not Install Stable

### ISSUE THREAD

**Issue by anmeng777** [fluttertools/sidekick#316]
I'm Sorry I live in China, internet is not good, could you please add a "mirror" setting in this project? Or are there other ways to use in China? I remember it works very well months ago. Please write a tutorial at your readme page, it will help a lot of developers.

thank you very much

have a nice day

**Comment by aguilaair** [comment]
Caused by: https://github.com/fluttertools/sidekick/issues/304

**Comment by charles0122** [comment]
@aguilaair maybe this issue means create mirror settings for china 

### maybe this resolve method is not  good, but really help many developer in china.

- [ ] **1. Adapt to the Chinese network environment change download url (https://docs.flutter.cn/release/archive)**
- [ ] **2. Tip china user  setting mirror sites or provider one click script to setting**


### refernences:

1. https://docs.flutter.cn/community/china

2. https://docs.flutter.cn/release/archive?tab=windows

**Comment by charles0122** [comment]
Additional links：
[https://fvm.app/documentation/advanced/custom-version#change-the-repository-url-to-the-fork](https://fvm.app/documentation/advanced/custom-version#change-the-repository-url-to-the-fork)

**Comment by anmeng777** [comment]
thank you very much
