### ISSUE TITLE
[Feature Request / Bug] Optimize Persist Single Instance For Windows

### ISSUE THREAD

**Issue by charles0122** [fluttertools/sidekick#318]
When I open another instance on Windows, an error occurs. This may be caused by the application positioning being a single-instance application. However, I think it can be optimized so that when I open another instance, no error message is displayed, but the instance window I have already opened is immediately displayed.

![image](https://github.com/user-attachments/assets/fb886a7b-248c-4e04-b909-9b62f0a02571)

**Comment by aguilaair** [comment]
Probably requires native code?

**Comment by charles0122** [comment]
As far as I know, that need to use native code. I have seen some information here.

from https://pub.dev/packages/window_manager
[Click the dock icon to restore after closing the window](https://leanflutter.dev/tips-and-tricks/002-click-dock-icon-to-restore-after-closing-the-window/)
[Making the app single-instanced](https://leanflutter.dev/tips-and-tricks/001-making-the-app-single-instanced/)

**Comment by aguilaair** [comment]
This definetely seems doable, feel free to make a PR or I can add it to my to-do
