### ISSUE TITLE
“Sidekick.app” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by Krammig** [fluttertools/sidekick#322]
“Sidekick.app” can’t be opened because Apple cannot check it for malicious software.

This software needs to be updated. Contact the developer for more information.

Chrome downloaded this file today at 11:47 am.

Appreciate your thoughts.

**Comment by aguilaair** [comment]
Please see: https://github.com/fluttertools/sidekick/wiki/Installing#installing-with-dmg-recommended

Let me know if you need additional help!
